sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root

  minio:
    endpoint: http://192.168.56.2:9000
    access-key: minio
    secret-key: minio123
    bucket-name: minio-demo